import type { Metadata } from "next";
import "./globals.scss";
import CustomCursor from "@/components/CustomCursor";
import Transitions from "@/components/Transitions";
import SmoothSroll from "@/components/SmoothScroll";

export const metadata: Metadata = {
  title: "Juan Borigen ~",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothSroll>
          <Transitions />
            {children}
          <CustomCursor />
        </SmoothSroll>
      </body>
    </html>
  );
}
